### ISSUE TITLE
Local errors are swallowed when using the module

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/cloud-errors-nodejs#75] opened 2016-11-29 07:06 UTC
I'm writing an app that uses the express middleware and the default configuration.  When my app crashes, I don't get a stacktrace in stderr.  It makes debugging an app with this installed really hard.

**Comment by ofrobots** [comment] 2016-11-29 07:15
Can you add a repro. I quickly tried it with the express sample app with the express middleware and the default configuration. I do get the stack trace.

```js
~/src/nodejs-docs-samples/appengine/express master* ⇣⇡ 56s
❯ npm start

> appengine-express@0.0.1 start /Users/ofrobots/src/nodejs-docs-samples/appengine/express
> node ./bin/www

GET / 304 238.159 ms - -
Error: CRASH!
    at /Users/ofrobots/src/nodejs-docs-samples/appengine/express/routes/index.js:24:9
    at Layer.handle [as handle_request] (/Users/ofrobots/src/nodejs-docs-samples/appengine/express/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ofrobots/src/nodejs-docs-samples/appengine/express/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/ofrobots/src/nodejs-docs-samples/appengine/express/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/ofrobots/src/nodejs-docs-samples/appengine/express/node_modules/express/lib/router/layer.js:95:5)
    at /Users/ofrobots/src/nodejs-docs-samples/appengine/express/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/ofrobots/src/nodejs-docs-samples/appengine/express/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/ofrobots/src/nodejs-docs-samples/appengine/express/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/ofrobots/src/nodejs-docs-samples/appengine/express/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/ofrobots/src/nodejs-docs-samples/appengine/express/node_modules/express/lib/router/index.js:46:12)
```

Code:
```js
var errors = require('@google/cloud-errors').start();
//...
app.use(errors.express);
```

**Comment by ofrobots** [comment] 2016-12-05 17:26
Ping @JustinBeckwith to provide a repro case.

**Comment by kilianc** [comment] 2017-03-28 06:49
+1 I have been missing errors for a week after integrating the library. No output to `stderr` and also I don't think it's correct that the module makes the call to kill the process.

In my example I had an validation error that I was throwing with `setImmediate` to let it show up in the console instead of just printing logs without explicitly calling `report`.

Correct behavior should probably be to report and re-throw, or give more behavior options.

Def `process.exit(1)` with no output is a bug.

**Comment by cristiancavalli** [comment] 2017-03-28 16:07
@kilianc Can you please provide some code which reproduces the case in question?

**Comment by kilianc** [comment] 2017-03-28 16:10
```js
require('@google/cloud-errors').start({
    ignoreEnvironmentCheck: true,
    serviceContext: {
      service: process.env.SERVICE_NAME,
      version: process.env.REVISION
    }
})

setTimeout(() => { throw new Error('This should appear in my console') })
```

This yields no output to `stderr`.

**Comment by cristiancavalli** [comment] 2017-03-28 16:20
@kilianc This is due to the behaviour of `process.on('uncaughtException', recv)` which the library uses to catch top-level errors and attempt to report them before the process exits. You may disable this behaviour and surface these errors to stderr by amending your configuration thusly:

```JS
require('@google/cloud-errors').start({
    ignoreEnvironmentCheck: true,
    reportUncaughtExceptions: false,    // This option defaults to true
    serviceContext: {
      service: process.env.SERVICE_NAME,
      version: process.env.REVISION
    }
})
```

**Comment by kilianc** [comment] 2017-03-28 16:23
@cristiancavalli that was clear, but the implementation is wrong because it doesn't print the error.

**Comment by cristiancavalli** [comment] 2017-03-28 16:26
@kilianc The implementation is not wrong. It is not the responsibility of the library to print the error. You may attach to this even yourself and print the error to stderr yourself if you so desire. To be clear: this is intended behavior. You may modify the libraries behaviour via the prior provided configuration or attach to the event earlier yourself and print out your error.

**Comment by kilianc** [comment] 2017-03-28 16:32
So just to be clear, it is **intended** behavior of this library to override the default node behavior of printing the exception to `stderr` and then exiting, with simply exiting (1) and leaving the user clueless.

I am very confused right now :)

P.S. if this stays the way it is, at least it's worth mentioning it in the README.

**Comment by cristiancavalli** [comment] 2017-03-28 16:38
@kilianc 

try this in a node script:

```JS
process.on('uncaughtException', () => console.log('caught'))
setImmeditate(() => {throw new Error('test')})
```

Notice how the error is swallowed and all that is printed out is `'caught'`?

This is not *overriding default behvaiour* it is, in fact, **unmodified** default behavior given the model of exception interception. This same model is extended to the error reporting library. Would you like to print-out uncaught exceptions with the library? Here are your options:

1. Before requiring the error reporting library attach an uncaughtException listener and print the output yourself.
2. Disable this behaviour by the library by providing the aforementioned change to your config.

Here's some reading on uncaughtException: 
https://nodejs.org/api/process.html#process_event_uncaughtexception

**Comment by cristiancavalli** [comment] 2017-03-28 16:52
@kilianc Informed, mature discussion is always wanted and welcome here but please make sure to inform yourself about the problem-space and background before simply stating something is 'wrong'.

Thanks and have a great day!

**Comment by cristiancavalli** [comment] 2017-03-28 17:01
@JustinBeckwith Closing for now given, please feel free to reopen given something does not seem right.

**Comment by kilianc** [comment] 2017-03-28 17:01
@cristiancavalli you are making a lot of assumption about what I did and what I didn't and what I know and what I don't know. This said, I am still 100% sure this implementation is wrong and you guys should fix it. For example we could check how many listeners are attached to `uncaughtException` or change default log level to print errors or any other way to not leave the user clueless because that's just bad design.

This said, I wish you a great day as well!

**Comment by cristiancavalli** [comment] 2017-03-28 17:11
@kilianc Thanks for your feedback. Again -- I'm not sure what's 'wrong' in this case. Wrong for your use-case? Potentially. Given your suggestion how about this scenario:

* We check to see at initialization that we are the only listener on the uncaughtException process event.
* Given that we the only one we now attempt to print all exceptions to stderr
* Someone later attaches to the event handler for custom error logging output
Now we have two libraries doing the same thing. Also there are cases where someone doesn't want this information printed to stderr, just sent to the server which is the purpose of the configuration. We are also a library that is meant to report errors to an error service, not act as a broker around who's handling what type of exception and who is printing it.

For development I would recommend that you develop with that configuration option changed to false. This way your errors won't be swallowed. When you're ready to deploy remove it if you would like to catch uncaught errors in production. This is a much more defined problem to solve and use in practice rather than trying to act like an undesignated third-party responsibility broker around the uncaughtException event and potentially causing conflicts with other modules.

**Comment by kilianc** [comment] 2017-03-28 18:00
```js
function uncaughtExceptionHandler(err) {
  var em = new ErrorMessage();

  // ------
  var shouldPrintError = !emitter.listeners('uncaughtException').length;
  if (shouldPrintError) console.error(err);
  // ------

  errorHandlerRouter(err, em);
  client.sendError(em, handleProcessExit);
  setTimeout(handleProcessExit, 2000);
}
```

**Comment by cristiancavalli** [comment] 2017-03-28 18:04
@kilianc I see your solution and its been duly noted for further consideration.
Once again we are not a broker for this behaviour nor are we interested in accepting this responsibility. If you would like to avoid the behaviour you are experiencing please use the provided configuration option. If that is not to your liking you can attach your own uncaughtException listener in this same format and call the error-reporting library yourself.

**Comment by kilianc** [comment] 2017-03-28 18:06
🍻

**Comment by fisch0920** [comment] 2017-03-28 20:09
Hey guys, just wanted to note that we've also been bitten by this and were surprised by the behavior that currently exists.  We do love using cloud-errors, though, so just want to chime in with my 2 cents ;)

Specifically, before integrating cloud-errors, we would get the default node uncaught exception handler that writes the exception and stack trace to stderr which would show up in our logs.  After integrating cloud-errors, this default behavior was overwritten and it took us awhile to figure out why we weren't seeing fatal errors anymore in our logs but were seeing them on cloud errors.

Following this thread, I fully understand what's going on now w.r.t. the cloud error library overriding the default uncaught exception handler, but I agree with some of the other folks on this thread that this behavior isn't obvious and either could be handled a bit better at the library-level via @kilianc's suggestion or at the documentation-level by a small addition to the docs explaining what I would expect to be a fairly common use case.

I hope you guys find this input helpful and overall, love using this great product!

**Comment by cristiancavalli** [comment] 2017-03-28 20:16
@fisch0920 @kilianc Noted and thanks for taking the time to articulate this valuable feedback.
I'll be discussing this with my lead as soon as he is available and my current leaning is to advocate for @kilianc's model with an option to specifically disable writing to stderr. That said, I realize this can be a controversial topic so I'll reopen this thread to hopefully collect more conversation about this potential new feature.

Thanks again for sharing your thoughts and feedback!

**Comment by ofrobots** [comment] 2017-03-29 22:24
The default behaviour is indeed surprising! I humbly apologize for the churn this has caused.

The proposal from @kilianc is pretty attractive; but the concern about the case where two (or multiple) unhandled exception handlers exists and none one takes ownership of writing to the console is also valid. Let us chew on this a bit more to come up some options.

**Comment by ofrobots** [comment] 2017-04-11 23:51
@kilianc @fisch0920 We decided to go with removing the *default* uncaught exception handling behaviour given the surprising behaviour and the existence of gotchas. Our README will now contain a clear 2-liner example on how to add an uncaught exception handler. Please take a look at the PR here: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2208 (Note that we are in the process of moving the code in this repo to https://github.com/GoogleCloudPlatform/google-cloud-node.)

We are very interested in your opinions – please do leave comments on the linked PR.

**Closed by ofrobots** 2017-04-11 23:51 UTC

**Comment by kilianc** [comment] 2017-04-17 20:34
@ofrobots @cristiancavalli I am so happy! Thanks for bearing with my frustrated rant. The good side of this is that at my company we now know `cloud-error` source code upside down 💃 

🍻

**Comment by ofrobots** [comment] 2017-04-17 20:41
@kilianc The new behaviour is now available through the newly published [@google-cloud/error-reporting](https://npm.im/@google-cloud/error-reporting) module. Thanks for your patience.
