### ISSUE TITLE
Module does not work with credentials generated by 'gcloud beta auth application-default login'

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-errors-nodejs#39] opened 2016-07-28 09:47 UTC
I did:
```
export GCLOUD_PROJECT=<your-project-id>
export NODE_ENV=production
```

Then `gcloud beta auth application-default login`

I installed the module version 0.0.3 (and also Debug and Trace)

Here is my app code:

```JS
require('@google/cloud-debug');
require('@google/cloud-trace').start();
var errorHandler = require('@google/cloud-errors')({
    serviceContext: {service: 'diagdemo'}
});

var express = require('express');
var app = express();

app.get('/', function (req, res) {

  try {
    will.crash();
  } catch(e) {
    console.log('reporting errors');
    console.log(e.stack);
    console.log(e);
    errorHandler.report(e);
  }
  res.send('Hello World!');
});

app.listen(8080, function () {
  console.log('Example app listening on port 8080!');
});
```

I can see traces in Stackdriver Trace and I can use debug.
But I cannot see reported errors.

Is it an application default credentials authentication problem? (see internal bug 30242004)

**Comment by steren** [comment] 2016-07-28 11:47
Note that if I use a service account and the GOOGLE_APPLICATION_CREDENTIALS envvar, it works.

**Comment by ofrobots** [comment] 2016-07-29 17:01
> Is it an application default credentials authentication problem?

Indeed. The default credentials from the `gcloud beta auth application-default` are used as a last resort. If you provide credentials through other means, e.g. `keyFilename` in config, an API key, or through `GOOGLE_APPLICATION_CREDENTIALS`, they take precedence.

**Comment by ofrobots** [comment] 2016-07-29 17:04
Closing as this is a duplicate of #10. The two fixes needed are: 1) fixing the precedence order (API was not taking precedence over application-default), and 2) internal bug with application default not working at all.

**Closed by ofrobots** 2016-07-29 17:04 UTC
Labels: bug
